f

diff --git a/github_actions/test/action.yml b/github_actions/test/action.yml
--- a/github_actions/test/action.yml
+++ b/github_actions/test/action.yml
@@ -20,6 +20,9 @@ outputs:
   error-code:
     description: 'The result of the Lua code execution'
     value: ${{ steps.handle-result.outputs.error-code }}
+  lua-error:
+    description: 'The result of the Lua code execution'
+    value: ${{ steps.handle-result.outputs.lua-error }}
 runs:
   using: "composite"
   steps:
@@ -73,6 +76,14 @@ runs:
       run: |
         mkdir -p pragma/lua
         scriptFileName="pragma/lua/ci_script.lua"
+
+        cat << 'EOF' > ${scriptFileName}
+        local cb = game.add_callback("OnLuaError",function(err)
+          file.write(\"ci.txt\", \"-1\")
+          file.write(\"ci_lua_error.txt\", err)
+        end)
+        EOF
+
         echo "file.write(\"ci.txt\", \"0\")" > ${scriptFileName}
         echo "${{ inputs.lua-code }}" >> ${scriptFileName}
         echo "file.write(\"ci.txt\", \"1\")" >> ${scriptFileName}
@@ -125,8 +136,15 @@ runs:
           exit $exit_code
         fi
 
+        CI_LUA_ERROR=$(cat "pragma/ci_lua_error.txt")
+        exit_code=$?
+        if [ $exit_code -ne 0 ]; then
+          echo "lua-error=$(echo ${CI_LUA_ERROR})" >> $GITHUB_OUTPUT
+        fi
+
         CI_CONTENTS=$(cat "pragma/ci.txt")
         exit_code=$?
+
         if [ $exit_code -ne 0 ]; then
           echo "error-code=3" >> $GITHUB_OUTPUT
           exit 1
